[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk/colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk/colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty/alacritty.toml'
output_path = '~/.config/alacritty/colors.toml'

[templates.dunst]
input_path = '~/.config/matugen/templates/dunst/dunstrc'
output_path = '~/.config/dunst/dunstrc'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel/colors.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.ewwii]
input_path = '~/.config/matugen/templates/ewwii/colors.scss'
output_path = '~/.local/share/oris/colors.scss'

[templates.niri]
input_path = '~/.config/matugen/templates/niri/colors.kdl'
output_path = '~/.config/niri/colors.kdl'
