[general]
import = ["colors.toml"]

[window]
padding.x = 10
padding.y = 10
startup_mode = "Maximized"
opacity = 0.98

[font]
normal.family = "FiraCode Nerd Font"
normal.style = "Bold"
size = 10.0

[cursor]
unfocused_hollow = false
blink_interval = 500

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"
